### ISSUE TITLE
Option to show menu on hover

### ISSUE THREAD

**Issue by mojtaba82** [Zren/material-decoration#16] opened 2020-07-24 16:23 UTC
Hi.
Thank you fot this nice decortion.
Please add feature to show menu only when hover on title bar.

**Comment by Zren** [comment] 2020-09-26 02:29
I already have background opacity animations, so making a reveal on hover animation isn't too difficult. The hard part is having the entire menu drawn in sync as the current bg hover animation is per button.

This will make all buttons transparent, and reveal just 1 button on hover.

```
QColor AppMenuButton::foregroundColor() const
{
    // ...
    } else {
        QColor hoverColor = Button::foregroundColor();
        QColor normalColor = QColor(hoverColor);
        normalColor.setAlphaF(0);

        return KColorUtils::mix(
            normalColor,
            hoverColor,
            opacity());
    }
}
```

**Comment by nicman23** [comment] 2020-10-30 12:38
can we have this without any animation?

**Comment by vosian** [comment] 2020-12-14 04:51
I'm also interested on this, even without animations

**Comment by Zren** [comment] 2021-01-13 17:03
The `menuonhover` branch has this feature. I now need to add a config option.

I need to figure out how I want to handle the caption. It currently "dodges" the menu which isn't needed when the menu is hidden.

I should probably do a comprehensive alignment option like Breeze.

* Left/Center/Right
* Center [between left/right buttons]
* Center (Full Width) [true center of window]
* Center (Full Width + Dodge Menu) [current MaterialDecoration behavior]

**Comment by Zren** [comment] 2021-01-13 17:06
Hmm. According to the Unity video https://youtu.be/nzFXRz-b3Ns?t=40

* Captions are left aligned
* Menu doesn't appear when hovered until the window is focused
* The title completely disappears, theres' no gradient (at least not in Ubuntu 14.04).

**Comment by nicman23** [comment] 2021-01-13 18:40
well all that could be configurable anyways (probably)

**Comment by mojtaba82** [comment] 2021-02-08 18:59
I fork this nice decoration. and add a branch named captionmenufeatcher and merge caption and menu like unity lim.
It work but I'm not professional in programming. I would be glad if you test it.
Thanks

**Comment by nicman23** [comment] 2021-02-09 10:18
hey adding to this, could we have the title of the window instead of empty space?

so on no hover -> title

on hover -> menu

**Comment by mojtaba82** [comment] 2021-02-09 10:45
@nicman23
> hey adding to this, could we have the title of the window instead of empty space?
so on no hover -> title
on hover -> menu

I implement this feature you want. you can compile and test it.
https://github.com/mojtaba82/material-decoration/commits/captionmenufeature

**Comment by Zren** [comment] 2021-02-09 18:54
* Caption will now hide on hover, and it's position ignores the space taken up by the menu.
* There's now a toggle in the config.
  * I used a hack to treat the "checkbox" as 2 radio buttons so that the on/off state has descriptive labels.
  * I need to bind the config toggle to redraw the menu.

**Comment by Zren** [comment] 2021-02-09 22:36
I've merged this feature and titlebar alignment to the `master` branch.

https://user-images.githubusercontent.com/416367/107437606-3e559b80-6afd-11eb-93a4-81d6525b715d.mp4

**Closed by Zren** 2021-02-09 22:36 UTC

**Comment by nicman23** [comment] 2021-02-10 07:45
small bug report, the menu is visible on window creation not the title

**Comment by Zren** [comment] 2021-02-10 22:42
Thanks for reporting the bug @nicman23. I fixed that bug and made the titlebar repaint when toggling always show.

**Comment by trmdi** [comment] 2021-02-18 16:18
Is this a related bug?

https://user-images.githubusercontent.com/11857205/108386766-897b5700-723f-11eb-91a0-feeb5dfcc870.mp4

**Comment by mojtaba82** [comment] 2021-02-18 16:27
I have same problem occasionally.

**Comment by Zren** [comment] 2021-02-18 18:55
The hover animation isn't checking if the menu is open atm. I did experience that once, but it rarely happens with Breeze's contextmenu.

Looks like I need to check `(m_currentIndex != -1)` in the `updateOpacity` func.

```
setOpacity(m_alwaysShow || m_hovered ? 1 : 0);
```

**Comment by trmdi** [comment] 2021-02-24 17:32
To reproduce it, you need to click at a point which is very close to the bottom edge of the button...

**Comment by mojtaba82** [comment] 2021-03-02 12:24
> To reproduce it, you need to click at points sit at the lower-half part of buttons...
> ![image](https://user-images.githubusercontent.com/11857205/109042042-4c610a00-7702-11eb-84b9-f9c2863db3d2.png)

I cinfirm this.

**Comment by Zren** [comment] 2021-03-07 15:55
Should be fixed with https://github.com/Zren/material-decoration/commit/d0267814ec81be025f732e9ef85a28076f56a813

Thanks @trmdi for your PR #34. I expanded on it to add a `bool showing` property which represents the `alwaysShow || hovered || isMenuOpen()`.
