### ISSUE TITLE
1px Colored Window Borders

### ISSUE THREAD

**Issue by giomatfois62** [Zren/material-decoration#35] opened 2021-03-04 10:23 UTC
Hi,
I love your decoration and would like to add a narrow border (1pixel ideally) colored as the accent color when the window is focused.
Something like windows10 does, as shown in this image  
 
![Screenshot (131)](https://user-images.githubusercontent.com/11869189/109949240-6b036a00-7cdb-11eb-801c-fecfb02bce9f.png)

with this it would be much easier to spot the currently focused window.  

I tried hacking this feature in your code, reserving border space on titlebar creation and adding draw calls in the paint event, but I could not get it to work properly (settings window decorations page crashes on decoration preview load, so i must be doing something very wrong).   

I'll keep experimenting on my own, but please consider adding this feature.
And thanks for creating this awesome decoration!

**Comment by Zren** [comment] 2021-03-04 15:19
Ah, I haven't implemented borders yet, so I should probably get around to that.

Use Breeze as an example. When the compositor is disabled, it draws an outline around the window.

* https://github.com/KDE/breeze/blob/master/kdecoration/breezedecoration.cpp#L545
* https://github.com/KDE/breeze/blob/master/kdecoration/breezedecoration.cpp#L571-L582

I'll get around to implementing the configurable `settings()->borderSize()` once I decipher it. I looks like the breeze code also has a window specific override which is not part of the KDecoration API which I'll have to ignore.

* https://github.com/KDE/breeze/blob/master/kdecoration/breezedecoration.cpp#L349

**Comment by giomatfois62** [comment] 2021-03-04 17:49
thanks for looking into this and for the heads up on the implementation :)
In the meantime, If I get something working on my own I'll send you a pull request just in case

**Comment by Zren** [comment] 2021-03-05 04:29
Well, I needed to fix a segfault caused by an `updateButtonGeometry()` getting called before the button groups where initialized.

After simplifying Breeze's `isLeftEdge()` functions (is window touching left edge), binding to boderSizeChanged, and modifying `updateBorders()` I discovered that most of my titlebar code doesn't take borders into account.

Here's what it looks like when I comment out `paintFrameBackground()` then draw a 1px outline.

![2021-03-04___22-00-28](https://user-images.githubusercontent.com/416367/110061145-0e349d80-7d35-11eb-86d5-4a3e00c66d2c.png)

```
void Decoration::paint(QPainter *painter, const QRect &repaintRegion)
{
    auto *decoratedClient = client().toStrongRef().data();

    if (!decoratedClient->isShaded()) {
        // paintFrameBackground(painter, repaintRegion);
    }

    paintTitleBarBackground(painter, repaintRegion);
    paintButtons(painter, repaintRegion);
    paintCaption(painter, repaintRegion);

    // Simple 1px border outline
    painter->save();
    painter->setRenderHint(QPainter::Antialiasing, false);
    painter->setBrush(Qt::NoBrush);
    painter->setPen(titleBarForegroundColor());
    painter->drawRect( rect().adjusted( 0, 0, -1, -1 ) );
    painter->restore();
}
```

```
void Decoration::updateBorders()
{
    const int sideSize = sideBorderSize();
    QMargins borders;
    borders.setTop(titleBarHeight());
    borders.setLeft(leftBorderVisible() ? sideSize : 0);
    borders.setRight(rightBorderVisible() ? sideSize : 0);
    borders.setBottom(bottomBorderVisible() ? bottomBorderSize() : 0);
    setBorders(borders);
}
```

**Comment by giomatfois62** [comment] 2021-03-05 20:37
Great Stuff!
If I understood correctly from your snippets, to draw just the decoration outline one only needs this calls?
```
    // Simple 1px border outline
    painter->save();
    painter->setRenderHint(QPainter::Antialiasing, false);
    painter->setBrush(Qt::NoBrush);
    painter->setPen(titleBarForegroundColor());
    painter->drawRect( rect().adjusted( 0, 0, -1, -1 ) );
    painter->restore();
```
It would be already enough for my needs!

**Comment by Zren** [comment] 2021-03-05 21:07
It's a bit more complicated that just drawing a rectangle. You need to change the left/right/bottom borders size, and doing so exposed a segfault bug when viewing the system monitor.

Here's my work in progress:

* https://github.com/Zren/material-decoration/tree/borders
* https://github.com/Zren/material-decoration/compare/master...borders

"Tiny" is a 1px line. With "Normal" being 1 "smallSpacing" size smaller than Breeze.

Right now I'm trying to fishing adjusting the left/right buttons, caption, and menu buttons offsets to account for the added borders as I can no longer assume the window contents are positioned at x=0 now that the left border pads it by a few pixels. I also need to decide if I want non-maximized windows should have the close button in the very top-right corner or if they should be pushed in to the left.

![2021-03-05___15-58-45](https://user-images.githubusercontent.com/416367/110172815-ab421580-7dcb-11eb-9068-f763eeeec9ec.png)
![2021-03-05___16-00-20](https://user-images.githubusercontent.com/416367/110172948-e47a8580-7dcb-11eb-89b3-0fb444f80428.png)
![2021-03-05___15-57-37](https://user-images.githubusercontent.com/416367/110172702-88176600-7dcb-11eb-9a7f-eaa5c771d7f2.png)

**Comment by Zren** [comment] 2021-03-06 19:11
To be honest, I'm not a fan of this much padding. I might use an offset for Oversized and use a padding for Tiny as it's just a 1px of padding. Or just forget the whole padding business.

![2021-03-06___14-09-11](https://user-images.githubusercontent.com/416367/110218054-8b6f2800-7e85-11eb-8581-610f63c72179.png)
![2021-03-06___14-08-41](https://user-images.githubusercontent.com/416367/110218055-8f9b4580-7e85-11eb-9338-ef1f55214f3b.png)

**Comment by Zren** [comment] 2021-03-06 21:38
The `borders` branch has been merged into `master`.

**Closed by Zren** 2021-03-06 21:38 UTC

**Comment by adrianinsaval** [comment] 2021-07-09 22:43
what color from the theme is used for the border? I would like to set a bright color for active windows and a dim color for inactive one's to make them easy to spot

**Comment by Zren** [comment] 2021-07-10 14:55
* `Decoration::paintOutline` https://github.com/Zren/material-decoration/blob/master/src/Decoration.cc#L1058

```cpp
    QColor outlineColor(titleBarForegroundColor());
    outlineColor.setAlphaF(0.25);
```

* `Decoration::titleBarForegroundColor()` https://github.com/Zren/material-decoration/blob/master/src/Decoration.cc#L930

```cpp
    const auto group = decoratedClient->isActive()
        ? KDecoration2::ColorGroup::Active
        : KDecoration2::ColorGroup::Inactive;
    return decoratedClient->color(group, KDecoration2::ColorRole::Foreground);
```

**Comment by adrianinsaval** [comment] 2021-07-10 20:35
thanks, if I change this line:  https://github.com/Zren/material-decoration/blob/e652d62451dc67a9c6bc16c00ccbc38fed3373dd/src/Decoration.cc#L1069
`painter->drawRect( rect().adjusted( 0, 0, -1, -1 ) );`
to have (0,0,-3,-3) will the outline be thicker or do I need something else?

What do you think of using the blend color for the outline instead of the foreground? That would allow to configure a more attention grabbing color like blue or green for the outline without making the text and buttons in the tittlebar look ugly. Just a suggestion, I will personally change the code to use the frame colors for my build.

**Comment by Zren** [comment] 2021-07-14 04:18
`rect().adjusted( 0, 0, -1, -1 )` takes the `QRect(x,y,width,height)` that represents the window frame, then subtracts 1 from the width and height so that when we draw the QRect stroke (aka outline), it will draw where we desire it to.

You need to set the `pen.setWidthF(3);` like in `Button::setPenWidth()`. You'll also probably need to `adjusted(2, 2, -3, -3)`.

* https://github.com/Zren/material-decoration/blob/master/src/Button.cc#L306

I just realized that the outline currently doesn't scale by DPI probably. 1080p and HiDPI both have an outline of 1px probably.
