### ISSUE TITLE
[Bug] Inconsitent spacing.

### ISSUE THREAD

**Issue by baduhai** [Zren/material-decoration#9] opened 2020-04-21 01:07 UTC
Pretty much as title describes, see screenshot.
![Screenshot_20200421_020658](https://user-images.githubusercontent.com/31864305/79813885-cb641400-8374-11ea-9090-f3e0a1b33cbc.png)

**Comment by Zren** [comment] 2020-04-21 23:47
This is likely caused by mnemonics (underlined with `Alt` usually). It uses `&File` for TextMetrics width, then hides them when drawn.

**Comment by Zren** [comment] 2020-04-22 00:14
Should be fixed.

**Closed by Zren** 2020-04-22 00:14 UTC
